on:
  workflow_dispatch:

jobs:
  hybrid-job:
    runs-on: ubuntu-latest

    steps:
      - name: Run on Ubuntu VM
        run: echo "This workflow runs on the Ubuntu VM"

      - name: Run inside Docker container
        uses: docker://alpine:3.14 # must be a public image to run it at step
        with:
          entrypoint: /bin/sh
          args: -c "echo 'This runs inside an alpine container'"

# to use a private docker image put all the process in single job 

  docrized_job:
    runs-on: ubuntu-latest
    container: node:20
    steps:
      - run : node --version
      - run : echo "run on private docker image "