on:
  workflow_dispatch:



jobs:
  workflow_command:
      runs-on: ubuntu-latest
      steps:
      - run: |
          deprecated="true" 
          if [[ deprecated ]] ; then 
          echo "::warning:: there is an deprecated func found"
          fi

      - name: Set Api Key
        run: echo "Api_key=12345" >> $GITHUB_ENV 

      - name: Get Api Key 
        run: echo "Api key is $Api_key"
      
      - name: check file exists
        run: |
          if [ -f "config.yaml" ]; then 
            echo "::debug::file 'config.yml' is exists"
          else 
            echo "::error::file 'config.yml' does not exists"
          fi
      - name: mask api key
        run: |
          echo "::add-mask::$Api_key"
          echo "using api key : $Api_key"
