on : 
    workflow_dispatch:


jobs:
    shell-job:
         runs-on: ubuntu-latest
         steps:
              - name: Run Shell Command
                run: echo "This workflow was triggered manually and is running a shell command!"

              # - run: |
              #     npm install
              #     npm run build
              #   working-directory: /tmp
              #   shell: bash

              - run : print %ENV
                shell: perl {0}