name : first workflow 

on : 
  push: 
    branches:
      - main
jobs:
  example-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print a Welcome Message
        run: echo "Welcome To Our GitHub Action Workflow!"

        
      - name: Checkout Repository
        uses: actions/checkout@v6.0.2

      - name: List Repository files
        run : ls -la
