on:
   workflow_dispatch:
     inputs:
       environment:
         description: 'Select the environment to deploy to'
         required: true
         default: 'staging'
         type: choice
         options:
           - production
           - staging
           - development
  
jobs:
  manual-job:
    runs-on: ubuntu-latest
    steps:
      - name: Run Manual Job
        run: echo "This workflow was triggered manually! with ${{inputs.environment}} as an environment selected."